### ISSUE TITLE
list-flume-agents

### ISSUE THREAD

**Issue by ozgebarbaros** [COMU/Fluman#19]
Arayüzde sistemde şu anda çalışan bütün flume agent'ların listelebilmesi gerekiyor. 

fluman merkezi bir yerde çalışan bir arayüz uygulaması olacak. 

bu yüzden networkde dağıtık olarak bulunabilecek olan flume agentlarının bilgisini "bir yerden" alabilmemiz gerekiyor. Flume mimarisi içinde bu ihtiyacı "master-node" karşılıyor. 

Fluman master-node ile nasıl konuşur ve sistemde çalışan flume agentları hakkında ne detayda bilgi alabilir bunun netleştirilmesi gerekiyor.

Örneğin, bir flume agent'in ismi, hangi ip'de çalıştığı, configurasyon dosyası gibi bilgiler elde edilebiliyor mu ?

**Comment by farukuzun** [comment]
#1 ile birleştiriyorum.
