### ISSUE TITLE
Bir Flume-agent'ın uzaktan configure edilmesi

### ISSUE THREAD

**Issue by ygokirmak** [COMU/Fluman#22]
Çalışan bir flume agent uzaktan configure edilebiliyor mu,
edilebiliyorsa nasıl? flume-master bunu yapabiliyor mu?

**Comment by farukuzun** [comment]
Bir flume agent'ın **_çalışırken**_ kontrol edilmesine rastlayamadım. Önce aynı kaynağı dinleyen yeni bir flume agent yapılandırılması oluşturulur. Ardından halihazırda çalışan durdurulur. Bu şekilde de aynı yetkiyi yaratabilir diye düşünüyorum.

Uzaktan kısmına gelirsek, Fluman nginx, apache gibi bir şey üzerinde çalışırsa ve gerekli izinlere sahip olursa internet üzerinden ulaşılıp flume'u kolayca yönetebilmesi, projenin amaçlarından.

Flume-master ile ilgili herhangi bir şeye son sürümde rastlayamadım, bug tracker'larını araştıracağım, eğer yoksa `pid`ler kontrol edeceğim gibi duruyor.

Not: yanılıyor olabilir, çünkü ben yalnızca tek bir makine ve ip üzerinde flume ile çalıştım.

**Comment by ygokirmak** [comment]
Flume agent'ın configurasyon dosyasını değiştiğinde flume kendisi otomatik olarak ayarları yüklüyor, o yüzden çalışırken ayarların değişmesi mevcutta desteklenen bir özellik.

fluman bir a makinesinde olmalı,
ama benim b,c,d,e,f,g,h makinalarında flume agentları var ve her makinada 10 ar tane agentım var diyelim..

a makinasındaki fluman arayüzünde bütün agentları yönetibiliyor olmamız lazım.. bu konuda aynı noktada mıyız?

flume-master'a ben de bakıyorum. o olmadan pid'ler ile olmaz bu iş..
network seviyesinde bir şekilde agent'ın merkezi bir deamonla konuşması gerekiyor.

**Comment by farukuzun** [comment]
O halde halihazırda varolan bir yapılandırma dosyasını düzenleme desteği eklenmeli.

A makinesinden b,c,d gibi makinelerdeki çalışan flume agent'ları nasıl kontrol ettirebiliriz bunu araştıracağım, şu an aklıma bir çözüm gelmiyor.

Flume'u ayar dosyalarıyla çalıştırıyorsanız bu dosyaları aynı yerde mi tutuyorsunuz?

**Comment by syigit** [comment]
Selam Faruk, 
Farklı makinelerdeki agentları nasıl yönetebiliriz, remote management konusunda birşey çıktı mı? Bu konuyla ilgili başka ayrıntılı sorular varsa dönüş yapabilirmisin.

**Comment by farukuzun** [comment]
Gecikmeler için üzgünüm ancak başlayabildim çalışmaya.
Bu konuyu araştırdım. `flume-master` yeni sürümlerde yok. Dağıtık flume kurulumu anlatımları ve yönetimi genelde eski sürümler üzerinden yapılmış.

Ağda dağıtık çalışan flume agent'larına ulaşmak için şimdilik aklıma gelen tek yöntem bunların yapılandırma (config) dosyalarının olduğu dizinleri belirlemek ve ulaşmak.

Bu konu hakkında ne düşünüyorsunuz?
Eğer uygunsa kafamdaki tasarımını buraya yazabilirim.

**Comment by ygokirmak** [comment]
Faruk, puppet, chef veya ansible aracılığıyla configurasyonun yönetilebileceğinden bahsettiler

@syigit  da bunu önermişti

Flume listesindeki adam şöyle yazmış

"
Monitoring and configuration are two separate things here.
Flume is typically monitored using either ganglia or http/json.
Both methods are documented here:
http://flume.apache.org/FlumeUserGuide.html#monitoring

As for configuration management and changes a common way of handling this would be to 
use a configuration management tool such as chef, puppet or ansible.
The agent polls the conf file every 30 seconds and if changes are detected than the necessary components will be dynamically reloaded.
"

puppet, chef, ansible'dan hangisini nasıl kullanacağımızı değerlendirmek lazım. ayrı bir issue acarak devam ediyorum

**Comment by farukuzun** [comment]
Bu konuyla ilgili çokca araştırma yaptım dün.
Bu işi yapan [Cloudera Manager](http://www.cloudera.com/content/support/en/documentation/manager-free/cloudera-manager-free-v4-latest.html) network'teki tüm makinelerle kendi belirlediği, kurulacak bir yazılım aracılığıyla konuşuyor.
Flume'ün eski sürümlerindeki master node yeni sürümlerine aktarılmamış. Eski sürümlerin dökümanlarında [şurada](http://archive.cloudera.com/cdh/3/flume/UserGuide/#_configuring_a_node_via_the_master) konudan bahsedilmiş.
Bu olayi mumkun kilmak için aklıma bir kaç şey geldi, yeni issue'da tartışalım.
