### ISSUE TITLE
Veritabanı Desteği

### ISSUE THREAD

**Issue by farukuzun** [COMU/Fluman#7]
Geliştirme süresi boyunca `sqlite` kullanacağım, ancak farklı veritabanları kullanmak isteyenler için anlaşılır dökümantasyon hazırlanmalı.

**Comment by ygokirmak** [comment]
sqlite özelinde birşey yapmadığımıza emin olmak için, 
postgres ve sqlite üzerinde çalışır halde tasarlamak daha isabetli olacaktır.
standart sql ve jdbc arayüzü kullanacağımızdan ek bir geliştirme eforu olmayacaktır

**Comment by farukuzun** [comment]
Kullandığım MVC Framework postgresql desteğine de sahip. Dökmana en kısa zamanda ekleyeceğim.
